INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('1', '100', 'Poltava', '762');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('2', '101', 'Suncheon', '271');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('3', '102', 'Tacloban', '681');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('4', '103', 'Darwin', '882');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('5', '104', 'El Quisco', '579');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('6', '105', 'Pekanbaru', '36');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('7', '106', 'Calbayog', '842');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('8', '107', 'Isabela City', '229');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('9', '108', 'Pontianak', '758');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('10', '109', 'Çermik', '32');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('11', '110', 'Alnwick', '220');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('12', '111', 'Vĩnh Trụ', '107');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('13', '112', 'Tomaszów Mazowiecki', '224');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('14', '113', 'Mokpo', '254');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('15', '114', 'Bama', '869');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('16', '115', 'Banbury', '6');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('17', '116', 'Jaén', '817');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('18', '117', 'Herstappe', '814');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('19', '118', 'Kendari', '977');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('20', '119', 'Tczew', '117');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('21', '120', 'Shangla', '418');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('22', '121', 'San Andrés', '473');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('23', '122', 'Motala', '903');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('24', '123', 'Mirpur', '341');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('25', '124', 'Nîmes', '829');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('26', '125', 'Lowestoft', '400');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('27', '126', 'Cossignano', '524');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('28', '127', 'San Rafael', '876');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('29', '128', 'Omsk', '161');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('30', '129', 'Jilin', '480');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('31', '130', 'Guadalupe', '351');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('32', '131', 'Blieskastel', '770');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('33', '132', 'Belfast', '680');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('34', '133', 'Mandai', '563');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('35', '134', 'Acireale', '877');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('36', '135', 'Dublin', '714');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('37', '136', 'Shanxi', '46');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('38', '137', 'Puntarenas', '115');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('39', '138', 'Matamata', '390');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('40', '139', 'Oleksandriia', '296');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('41', '140', 'Sechura', '464');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('42', '141', 'Flushing', '186');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('43', '142', 'Berlin', '409');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('44', '143', 'Pskov', '331');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('45', '144', 'Heilongjiang', '796');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('46', '145', 'Logroño', '528');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('47', '146', 'Lloydminster', '959');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('48', '147', 'Warszawa', '533');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('49', '148', 'Rutigliano', '929');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('50', '149', 'Huara', '720');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('51', '150', 'Oss', '541');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('52', '151', 'San Pedro', '544');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('53', '152', 'San Andrés', '21');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('54', '153', 'Kuruman', '703');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('55', '154', 'Oviedo', '402');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('56', '155', 'Dordrecht', '218');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('57', '156', 'Monterrey', '568');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('58', '157', 'Rzeszów', '877');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('59', '158', 'Putre', '558');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('60', '159', 'Dhule', '921');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('61', '160', 'Kurgan', '255');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('62', '161', 'A Coruña', '586');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('63', '162', 'Guadalajara', '29');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('64', '163', 'Pskov', '294');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('65', '164', 'Dublin', '818');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('66', '165', 'Jerzu', '843');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('67', '166', 'Smolensk', '21');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('68', '167', 'Wellington', '100');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('69', '168', 'Bergerac', '162');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('70', '169', 'Beypazarı', '296');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('71', '170', 'Berlin', '8');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('72', '171', 'Acuña', '922');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('73', '172', 'Dos Hermanas', '2');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('74', '173', 'Stratford', '338');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('75', '174', 'Ningxia', '830');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('76', '175', 'Punggol', '479');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('77', '176', 'Helena', '734');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('78', '177', 'Lamont', '278');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('79', '178', 'Jaipur', '798');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('80', '179', 'Asan', '353');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('81', '180', 'Bhiwandi', '528');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('82', '181', 'Suwałki', '538');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('83', '182', 'Puntarenas', '163');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('84', '183', 'Bandırma', '285');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('85', '184', 'Khmelnytskyi', '710');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('86', '185', 'Göteborg', '908');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('87', '186', 'Woodlands', '412');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('88', '187', 'Shangla', '7');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('89', '188', 'Trollhättan', '328');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('90', '189', 'Sembawang', '291');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('91', '190', 'Zoetermeer', '162');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('92', '191', 'Jaén', '872');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('93', '192', 'Okigwe', '517');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('94', '193', 'Aurillac', '473');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('95', '194', 'Sembawang', '303');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('96', '195', 'Tibet', '480');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('97', '196', 'Quillota', '438');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('98', '197', 'Vienna', '504');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('99', '198', 'Upper Hutt', '80');
INSERT INTO "main"."sucursal" ("branch_id", "branch_number", "branch_name", "branch_address_id") VALUES ('100', '199', 'Iqaluit', '577');